externalImagePath: home/ssm-user/seb44_main_026/images/
spring:
  log-request-details: true
  #mvc:
  #  static-path-pattern: /images/**
  #resources:
  #  static-locations: file:${externalImagePath}

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "https://greennare-service-457336470984.us-central1.run.app/login/oauth2/code/google"
            scope: email, profile
#              - email
#              - profile

  cache:
    type: redis

  redis:
#    cache:
    host: 34.45.8.145
    port: 6379

  datasource:
    url: jdbc:mysql://34.173.185.16:3306/greennare?serverTimezone=Asia/Seoul
    username: greennare-user
    password: GreennareUser1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


#  h2:
#    console:
#      enabled: true
#      path: /h2

#  jpa:
#    defer-datasource-initialization: true
#    database-platform: H2
#    hibernate:
#      ddl-auto: create-drop

    open-in-view: false

    properties:
      show-sql: true
      hibernate:
        format_sql: true
        use_sql_comments: true

  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:greennare-9e6b24e727ac.json
        project-id: greennare
        bucket: greennare-bucket-1

#  datasource:
#  #    url: jdbc:mysql://34.64.148.174:3306/greennare?serverTimezone=Asia/Seoul
#  #    username: api
#  #    password: api
#  #    driver-class-name: com.mysql.cj.jdbc.Driver
#
#    url: jdbc:h2:mem:test
#    username: sa
#    driver-class-name: org.h2.Driver


  sql:
    init:
      #schema-locations: classpath*:db/h2/schema.sql
      #data-locations: classpath*:db/h2/data.sql
#  application:
#    name: monitoring
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG

#    org:
#      springframework: DEBUG
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

#    org:
#      springframework:
#        jdbc:
#          core: TRACE

jwt:
  key: jasdfasfd1312345351354314560984745
  access-token-expiration-minutes: 1
  refresh-token-expiration-minutes: 10

mail:
  address:
    admin: admin@gmail.com

#management:
#  endpoint:
#    metrics:
#      enabled: true
#    prometheus:
#      enabled: true

# endpoints:
#    web:
#      exposure:
#        include: health, info, metrics, prometheus

# metrics:
#    tags:
#      application: ${spring.application.name}