#externalImagePath: C:/Users/eheka/seb44_main_026/images/
externalImagePath: /home/ssm-user/seb44_main_026/images/
spring:
  mvc:
    static-path-pattern: /images/**
  resources:
    static-locations: file:${externalImagePath}

  jpa:
    hibernate:
      ddl-auto: none

    open-in-view: false

    properties:
      hibernate:
        format_sql: true
        show_sql: true

  redis:
    cache:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mysql://greennare-db.cvohnsqc7tsw.ap-northeast-2.rds.amazonaws.com:3306/greennare
    username: admin
    password: greennare
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      data-locations: classpath*:db/schema.sql

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE

jwt:
  #key: ${JWT_SECRET_KEY}
  key: jasdfasfd1312345351354314560984745
  access-token-expiration-minutes: 120
  refresh-token-expiration-minutes: 420

mail:
  address:
    admin: admin@gmail.com