steps:
  - id: 'deploy-workflow'
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'greennare-service', '--image', 'gcr.io/$PROJECT_ID/my-image', '--region', 'us-central1']

images:
  - 'gcr.io/$PROJECT_ID/my-image'